### ISSUE TITLE
Report endpoint

### ISSUE THREAD

**Issue by bpglaser** [toastymmm/server#22]
There isn't an endpoint listed on swagger for reporting a message.

**Comment by nikdunn** [comment]
That's the point of the PATCH endpoint. If we think of messages as resources, then PATCH provides the ability to modify existing resources. Since anyone can report a message via the mobile app we'll need to be more precise about the access control, but using the PATCH in that way is more RESTful IMHO.

**Comment by bpglaser** [comment]
I assumed that the PATCH endpoint was for editing a message. Reporting a message is something that anyone can do to anyone else's message. Because of that, I foresee a race condition if two users try to report a message at the same time by just incrementing numReports. i.e. they both increment the same number and it is only reported once instead of twice.

**Comment by nikdunn** [comment]
That's true, a race condition would always exist in network code like this. Even if we had a specific increment message, we'd still have to handle the synchronization of multiple simultaneous requests. If it were a multi-threaded application you could potentially have a race condition between two threads. Node is single threaded, but if Message In A Bottle were scaled up to where there were multiple processes or servers handling requests the race condition would appear in those as well.

Ideally the database implements some sort of transaction system or an increment operator where you could lock an object, write to the database, and then unlock it or modify it atomically. At some point concurrent writes would need to be resolved. It's an ugly problem and limitation in a highly concurrent system without a lot of really useful options. MongoDB for example has a sharding database models where you can have multiple readers, but only one writer. The reader databases are made "eventually consistent" with the primary one. 

Even with an increment style event, you aren't really doing REST anymore. You're implementing a Remote Procedure Call on a database object. Here's an article I found that describes the difference. https://blog.jscrambler.com/rpc-style-vs-rest-web-apis/

I admit to trying to be kind of a purist regarding the REST concept, but REST certainly has its limitations.

Even the "/me" endpoints are a little non-REST-y in my opinion, but I agree they are convenient. Things like collections still fit in REST because they are collections of resources.

That's my 2 cents, anyway.

I'm not opposed to an REST/RPC hybrid if it's useful.

**Comment by bpglaser** [comment]
I agree with everything stated. However, having a report fail or continuously retry on the client seems like foolishness.

**Comment by nikdunn** [comment]
Why would it fail?

**Comment by bpglaser** [comment]
I suppose that it wouldn't. It would just overwrite someone else's edit. Which, in my opinion is a bigger problem. The race condition when incrementing the reports would also overwrite someone's in-progress edit, no? Since an edit and a report are both subject to the same race condition.

**Comment by nikdunn** [comment]
Well that case would only exist between an admin and a creator.

One way I've seen that handled is to reject the attempt to update the record and let the second editor see the new data before finalizing the change.

Another way you could resolve the race is requiring a copy of the old object so the API can compute what the change was.

**Comment by c650** [comment]
For reporting specifically, if we did have a report endpoint we could make a new type in the database called Report and let it act on a message. But that seems like a lot of work to do now, since we don't need to worry about that level of scale just yet.

**Comment by nikdunn** [comment]
Right! That would be a more REST-ful way to do it.

**Comment by c650** [comment]
I suppose I don't mind but I don't think it's worth doing rn

**Comment by nikdunn** [comment]
I feel a little like a REST grammar nazi, though. I don't have a strong opinion either way. TBH, I don't think we'll hit the race condition either. And if we do, welp? It's got a bug or two.

**Comment by c650** [comment]
Race condition unlikely until we have high user volume

**Comment by c650** [comment]
Even then, our current implementation allows for a user to report the same message possibly infinite times

**Comment by bpglaser** [comment]
Unless there is validation on the backend, it would also allow a user to "unreport" things too.

**Comment by c650** [comment]
#37 :)
